OkunaOrg/okuna-api

- openbook_communities/tests/views/communities/test_views.py
- openbook_communities/views/communities/views.py
Fixes https://github.com/OpenbookOrg/openbook-api/issues/181
> :bug: fix cannot infinite scroll my communities

- openbook_auth/models.py
- openbook_posts/models.py
- openbook_posts/tests/views/test_post.py
- openbook_posts/tests/views/test_posts.py
- openbook_posts/views/post/views.py
This reverts commit f975b567ffaeb34b774d7a3d4f7bca135b53d2f0, reversing
changes made to 7cf52aad17ccefdd75f44a4a7f50214f90488df0.
#	openbook_auth/models.py
> Revert "Merge pull request #244 from OpenbookOrg/release/0.0.28"

- openbook_auth/models.py
This reverts commit b159f23fb6e00b415527e486de445bb3c759dc55.
> Revert ":bug: bring back old timeline"

- .circleci/config.yml
- openbook_auth/models.py
This reverts commit 086bb944565add3f7b8d82e02d86d3366111e5ee, reversing
changes made to 703d2ce8e1ec0afc609eefc29f85e3a5bd98886b.
Unfourtunately the timeline posts query is still an issue...
> Revert "Merge pull request #255 from OpenbookOrg/acceptance"

- openbook_communities/views/community/posts/serializers.py
Fixes https://github.com/OpenbookOrg/openbook-app/issues/141
> :bug: fix dissapearing reactions in communities

- README.md
First things first, when working on a new project: Improve documentation :-)
I wasn't able to build the project via `pipenv` until I installed libmagic and MySQL.
> Updated the prerequisites section

- openbook_communities/views/community/members/serializers.py
Get community members was missing is_following and is_connected
> :bug: include is_following and is_connected to get community members

- openbook_auth/models.py
- openbook_communities/models.py
- openbook_communities/tests/views/communities/test_views.py
- openbook_communities/tests/views/community/banned_users/test_views.py
- openbook_communities/tests/views/community/members/test_views.py
- openbook_communities/tests/views/community/moderators/test_views.py
- openbook_communities/tests/views/community/posts/test_views.py
- openbook_communities/tests/views/community/test_views.py
- openbook_communities/views/communities/views.py
- openbook_posts/models.py
- openbook_posts/tests/views/test_post.py
- openbook_posts/tests/views/test_posts.py
- openbook_posts/views/posts/views.py
users wont be able to see the community, wont appear in searches, wont be able to comment/react to posts inside, wont see trending posts from it, nor will see it on trending communities
Fixes #200
> :sparkles: add community banning access/action control

- docs/COMMUNITY_GUIDELINES.md
Unfortunately, as seen recently, people might abuse the fact that nudity isn't in there to snuggle porn into the platform..
I'm up for allowing non-sexual/artistic nudity on the platform but not before we have reporting and NSFW filters in place.
> :memo: add nudity to porn statement

- .circleci/config.yml
- utils/make_admin_headers.py
- utils/templates/eb_extensions/admin.conf.yml
- utils/templates/eb_extensions/block_admin.conf.yml
Because some things are to be hidden.
> :lock: Trying to shield some things

- utils/templates/eb_extensions/admin.config.yml
- utils/templates/eb_extensions/block_admin.config.yml
Otherwise EB does not play nice.
> :rocket: Renaming conf -> config

- utils/make_admin_headers.py
Forgot the rename the vars in the script.
> :bug: :facepalm: Not such a smart move

- .circleci/config.yml
Testing to see if the admin restriction works straight away
> :rocket: Merge admin changes into develop

- openbook_auth/templates/openbook_auth/email/change_email.html
- openbook_auth/templates/openbook_auth/email/change_email.txt
- openbook_auth/templates/openbook_auth/email/reset_password.html
- openbook_auth/templates/openbook_auth/email/reset_password.txt
- openbook_common/templates/openbook_common/email/footer.html
- openbook_invitations/templates/openbook_invitations/email/backer_alternate_username.html
- openbook_invitations/templates/openbook_invitations/email/backer_alternate_username.txt
- openbook_invitations/templates/openbook_invitations/email/backer_onboard.html
- openbook_invitations/templates/openbook_invitations/email/backer_onboard.txt
- openbook_invitations/templates/openbook_invitations/email/user_invite.html
- openbook_invitations/templates/openbook_invitations/email/user_invite.txt
We can't change app names as database generic relationships use this to map items + all model tables have them as prefix.
> :recycle: change mail templates on okuna

- openbook_notifications/django_rq_jobs.py
- openbook_notifications/helpers.py
See https://github.com/rq/django-rq/issues/358
> :bug: do not pass entire user instance to django rq job

- docker-compose.yml
https://github.com/OkunaOrg/okuna-api/issues/512
> Bugfix/512 Default character set to `utf8` and collation to `utf8_unicode_ci`

- README.md
Add documentation detailing how to override docker settings (network, volume, etc)
> Add docker override documentation

- docs/COMMUNITY_GUIDELINES.md
Update the text and the links in the community guidelines to reflect the name change to Okuna
> :pencil: :speech_balloon: Change Openbook to Okuna and update the links

- openbook_circles/serializers.py
- openbook_communities/views/community/administrators/serializers.py
- openbook_communities/views/community/banned_users/serializers.py
- openbook_communities/views/community/members/serializers.py
- openbook_communities/views/community/moderators/serializers.py
- openbook_communities/views/community/serializers.py
- openbook_connections/serializers.py
- openbook_follows/serializers.py
- openbook_lists/serializers.py
- openbook_moderation/serializers.py
- openbook_moderation/views/moderated_object/serializers.py
- openbook_moderation/views/user/serializers.py
- openbook_notifications/serializers.py
- openbook_posts/views/post_comment/post_comment_reaction/serializers.py
- openbook_posts/views/post_reaction/serializers.py
fixes https://github.com/OkunaOrg/okuna-app/issues/282
some users find it annoying that badges arent consistent.. also in circles the pending status is not shown if someone hasnt accepted the request yet.
> :bug: add badges serializer to all userprofile serializers

- .ebextensions/health_worker.config
Path needs to have two spaces less? Is that the issue? No clue otherwise.
> :bug: Two f***ing spaces

- openbook_common/serializers.py
- openbook_hashtags/views/hashtag/serializers.py
> :bug: add is_encircled and circles to hashtag posts

- openbook_common/utils/helpers.py
I forgot to add the luminance change for new hashtags
> :recycle: new hashtags with luminance -20

- .ebextensions/supervisord.config
> :ambulance: Change runas user

- .ebextensions/supervisord.config
We also have a different pid file for each individual worker.
> Set the right permissions for the pid files

- .ebextensions/supervisord.config
> Run workers with lower privz

- Pipfile.lock
This reverts commit bb5c96ec8060661732a2e0deb8cc945d501dfdb3.
> Revert ":package: update Pillow"
